### ISSUE TITLE
Attachment Circuit - Terminology Change

### ISSUE THREAD

**Issue by jlivingood** [boucadair/draft-xxx-ac-rate-policy-discovery#15]
Suggesting changing from 'circuits' - since mobile and other IP networks are packet-based. Maybe some other term can be used.

**Comment by jlivingood** [comment]
I see that AC is used in linked docs - perhaps this is a 3GPP term?

**Comment by boucadair** [comment]
Hi Jason,

"Attachment circuit" is an established concept in IP/MPLS networks, you can see, for example, 

* https://datatracker.ietf.org/doc/html/rfc4026#section-6.1
* https://datatracker.ietf.org/doc/html/rfc4364#section-3.1
* https://datatracker.ietf.org/doc/html/rfc8049#section-3
* https://datatracker.ietf.org/doc/draft-ietf-opsawg-teas-common-ac/
* https://datatracker.ietf.org/doc/draft-ietf-opsawg-teas-attachment-circuit/
* https://datatracker.ietf.org/doc/draft-ietf-opsawg-ntw-attachment-circuit/
* etc.

The term "circuit" is also used in the transport layer, e.g., circuit breaker (https://datatracker.ietf.org/doc/rfc8084/)

I agree that it is unfortunate that "circuit" was picked at the first place, but we reusing this concept helps gluing various pieces that are already out there and also help generalizing the applicability. 

For example, an AC can be UNI or NNI. Hence, s/ac/access network may not be adequate to mirror that scope as well.

What about "network attachment"?

**Comment by danwing** [comment]
“Network attachment” is great

**Comment by boucadair** [comment]
Thanks Dan. Went with "network attachment" in the abstract for now.

**Comment by jlivingood** [comment]
+1 to network attachment - great idea!
