### ISSUE TITLE
Add some explanation for the need to have a reliability flag

### ISSUE THREAD

**Issue by boucadair** [boucadair/draft-xxx-ac-rate-policy-discovery#37]
@sridharangirish91, can you please propose some text to https://github.com/boucadair/draft-xxx-ac-rate-policy-discovery/blob/main/draft-brw-scone-throughput-advice-blob.md to motivate the need to have reliability flag? Thanks

**Comment by tireddy2** [comment]
I don't think it is possible to distinguish between reliable and unreliable traffic in QUIC. How is rate-limit policy enforced by networks today for QUIC traffic ?

**Comment by danwing** [comment]
> I don't think it is possible to distinguish between reliable and unreliable traffic in QUIC. 

For network to distinguish, the sender would have to set a bit somewhere.  DSCP bit, a certain QUIC short CID, IPv6 hop-by-hop option, *something*.

**Comment by tireddy2** [comment]
DSCP values cannot be typically applied for incoming traffic. The hop-by-hop option also faces deployment challenges. I am not aware of any deployments where CID is used by networks to distinguish between reliable and unreliable traffic.

I suggest to remove it and keep the 00 version simple.

**Comment by danwing** [comment]
> DSCP values cannot be typically applied for incoming traffic.

Better tell the L4S proponents!

**Comment by jlivingood** [comment]
> DSCP values cannot be typically applied for incoming traffic. 

That is not correct. Most ISPs will re-write DSCP on ingress flows. For NQB, ISPs are preserving DSCP-45 e2e. 

> The hop-by-hop option also faces deployment challenges. I am not aware of any deployments where CID is used by networks to distinguish between reliable and unreliable traffic.

If unreliable vs reliable the same as NQB vs QB?

**Comment by jlivingood** [comment]
> DSCP values cannot be typically applied for incoming traffic. 

That is not correct. Most ISPs will re-write DSCP on ingress flows. For NQB, ISPs are preserving DSCP-45 e2e. 

> The hop-by-hop option also faces deployment challenges. I am not aware of any deployments where CID is used by networks to distinguish between reliable and unreliable traffic.

If unreliable vs reliable the same as NQB vs QB?

**Comment by jlivingood** [comment]
> DSCP values cannot be typically applied for incoming traffic. 

That is not correct. Most ISPs will re-write DSCP on ingress flows. For NQB, ISPs are preserving DSCP-45 e2e. 

> The hop-by-hop option also faces deployment challenges. I am not aware of any deployments where CID is used by networks to distinguish between reliable and unreliable traffic.

If unreliable vs reliable the same as NQB vs QB?

**Comment by tireddy2** [comment]
> > DSCP values cannot be typically applied for incoming traffic.
> 
> Better tell the L4S proponents!

DSCP values can be modified by at any place in the network and I don't think the application can be trusted to set the correct DSCP value.

**Comment by tireddy2** [comment]
> > DSCP values cannot be typically applied for incoming traffic.
> 
> That is not correct. Most ISPs will re-write DSCP on ingress flows. For NQB, ISPs are preserving DSCP-45 e2e.
> 
> > The hop-by-hop option also faces deployment challenges. I am not aware of any deployments where CID is used by networks to distinguish between reliable and unreliable traffic.
> 
> If unreliable vs reliable the same as NQB vs QB?

Yes, reliable would be mapped to QB and unreliable to NQB but the network has no visibility of such information on a QUIC flow which could have both unreliable and reliable streams.

**Comment by boucadair** [comment]
> Yes, reliable would be mapped to QB and unreliable to NQB but the network has no visibility of such information on a QUIC flow which could have both unreliable and reliable streams.

That's the call of the app. The considerations in https://datatracker.ietf.org/doc/html/[draft-ietf-tsvwg-nqb-27](https://datatracker.ietf.org/doc/html/draft-ietf-tsvwg-nqb-27#name-dscp-marking-of-nqb-traffic)#name-dscp-marking-of-nqb-traffic may be followed. The marking will thus be visible.

Of course, I don't think we say this is the only way to do it and that a network have to create policers for both.
