### ISSUE TITLE
Throughput advice

### ISSUE THREAD

**Issue by tireddy2** [boucadair/draft-xxx-ac-rate-policy-discovery#38]
rate-limit =  {
     cir: uint,    ; Mbps
     cbs: uint,    ; bytes
     ? eir: uint,  ; Mbps
     ? ebs: uint,  ; bytes
     ? pir: uint,  ; Mbps
     ? pbs: uint   ; bytes
   }

I assumed cir and cbs are sufficient to be conveyed to the client, what is the need to convey the other rates and how is the client supposed to react to each of the rates differently ?

**Comment by tireddy2** [comment]
Which two last paragraphs are you referring in 4115 ?
It is not clear to me how the client will react differently by learning the eir, ebs, pir and pbs rates ?
For instance, in case of 1r2c, the client only has to enforce the traffic does not exceed cir and cbs. what will it do with the other two parameters eir and ebs ?
How will the client identify the burst duration using cbs ?

**Comment by boucadair** [comment]
I was referring to,

> The metering/marker defined here is different from those in [[RFC2697](https://www.rfc-editor.org/rfc/rfc2697)]
>    and [[RFC2698](https://www.rfc-editor.org/rfc/rfc2698)].  It is different from [[RFC2697](https://www.rfc-editor.org/rfc/rfc2697)] in that it is a two-
>    rate, three-color marker.  In contrast, [[RFC2697](https://www.rfc-editor.org/rfc/rfc2697)] is a single-rate
>    marker.  It is different from [[RFC2698](https://www.rfc-editor.org/rfc/rfc2698)] in the way its parameters are
>    defined, which allows a better handling of in-profile traffic for
>    predominant service scenarios over a wider range of traffic
>    parameters.
> 
>    Furthermore, the algorithm described here eliminates the need for the
>    CE to shape its traffic to a certain peak information rate (PIR), as
>    might be the case for the marker defined in [[RFC2698](https://www.rfc-editor.org/rfc/rfc2698)] when the value
>    for the peak burst size (PBS) is smaller than that for the committed
>    burst size (CBS).

These parameters are already for the provisioning of CEs for some services. See, e.g., https://datatracker.ietf.org/doc/rfc8466/ (search for svc-bandwidth).

**Comment by tireddy2** [comment]
Thanks for the info, I was aware that PBS could be slower than CBS; it will helpful to add a pointer to this paragraph.

**Comment by boucadair** [comment]
Sure. Created https://github.com/boucadair/draft-xxx-ac-rate-policy-discovery/pull/45 to address this.
