### ISSUE TITLE
Comments on CDDL

### ISSUE THREAD

**Issue by tireddy2** [boucadair/draft-xxx-ac-rate-policy-discovery#39]
1.  In tc, the field tc: uint has the same name as the containing structure, which could lead to confusion. please rename this field.
2.  In opf and ff, you may want to use "false" instead of "0".

**Comment by boucadair** [comment]
Good catch. Please see #40 

BTW, in order to save some space, I guess we need to have tree values for direction (n2h, h2n, both). Otherwise, we will need to repeat the same parameters twice to cover the case where the same policy is applied for both directions.
