### ISSUE TITLE
Define groups: (C*+E*) or (C*+P*)

### ISSUE THREAD

**Issue by tireddy2** [boucadair/draft-xxx-ac-rate-policy-discovery#55]
My understanding is if EIR, EBS are conveyed in the metadata, PIR and PBS must not be signaled and vice-versa. we will have re-define the CDDL in the following way:

rate-limit = (
  group-a / group-b
)

group-a = {
  cir: uint,          ; Mbps
  cbs: uint .gt 0,    ; bytes
  ? eir: uint,        ; Mbps
  ? ebs: uint .gt 0   ; bytes
}

group-b = {
  cir: uint,          ; Mbps
  cbs: uint .gt 0,    ; bytes
  ? pir: uint,        ; Mbps
  ? pbs: uint .gt 0   ; bytes
}

**Comment by sridharangirish91** [comment]
I couldn't find RFCs to refer but in practical deployments, can there be a case where a packet exceeds CBS but is within PBS, so is EBS used in that case to have a more lenient window (like packets > CBS but < EBS to be treated with lower(lowest) priority and drop the ones that exceed PBS?

**Comment by tireddy2** [comment]
my understanding is (EIR, EBS) and (PIR and PBS) are mutually exclusive.

**Comment by boucadair** [comment]
Tiru is right. As indicated in the analysis ID, typical combinations are these in https://s3-docs.fd.io/vpp/23.06/developer/corefeatures/policer.html. 

Other implems (Juniper) can be seen here as well: https://www.juniper.net/documentation/us/en/software/junos/cos/topics/task/cos-configuring-tricolor-marking-policers.html or https://www.juniper.net/documentation/us/en/software/junos/routing-policy/topics/concept/policer-overview.html
