### ISSUE TITLE
reactive policy

### ISSUE THREAD

**Issue by tireddy2** [boucadair/draft-xxx-ac-rate-policy-discovery#57]
-	Should there be mentioned already in the Abstract for the reactive policy as an additional example the limited capacity due to varying radio connection conditions (now there are mentioned the overload and DDoS attach mitigation)? The “issue with RAN resources” is mentioned though in the Sample Deployment Cases, so don’t know if this is already enough.

**Comment by boucadair** [comment]
the old issues are  split into individual issues #58 #59 #60
