### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by tireddy2** [boucadair/draft-xxx-ac-rate-policy-discovery#72]
1. Also, one or more throughput advice instances may be returned for a given traffic direction. Each of these instances may cover a specific traffic category. Examples of such instances are discussed in {{sec-ex}}.

Comment> Is this line required (now that the draft does not discuss multiple traffic categories) ?

2. How applications running over a host can learn the bitrates associated with a network attachment. Typically, this can be achieved by invoking a dedicated API. However, the exact details of the API is OS-specific and, thus, out of scope of this document.

Comment> It is not clear whether OS-specific APIs are required not. I would remove the last line. MASQUE and QUIC based proposals don't require OS-specific API.

3. The services or applications that are delivered over a network attachment. Whether one or multiple services are bound to the same network attachment is deployment specific.

Comment> I don't get how the above line is relevant for this draft. What is the use case for a single service being bound to a network attachment ? 

The network has no clue whether it is a single or multiple applications with QUIC (and TLS ECH).

4. Adaptive Application Behavior: : Discovery of intentional policy applied on network attachements when such information is not made available during the service activation or when network upgrades are performed. Adaptive applications will use the information to adjust their behavior. : Concretely, applications are supposed to have access to all throughput advice instances and would, thus, adjust their behavior as a function of scope and traffic category indicated in a throughput policy (all traffic, streaming, etc.). An application that couples multiple flow types will adjust each flow type to be consistent with the specific policy for the relevant traffic category. : Likewise, a host with multiple network attachments may use the discovered throughput advice instances over each network attachment to decide how to distribute its flows over these network attachments (prefer a network attachment to place an application session, migrate connection, etc.). That's said, this document does not make any recommendation about how a receiving host uses the discovered policy.

Comment> I see the discussion on traffic category (which can be avoided for now).

5. I don't see a need for "Security Considerations" Section to focus on DDoS.

**Comment by boucadair** [comment]
> 1. Also, one or more throughput advice instances may be returned for a given traffic direction. Each of these instances may cover a specific traffic category. Examples of such instances are discussed in {{sec-ex}}.
> 
> Comment> Is this line required (now that the draft does not discuss multiple traffic categories) ?

It is as it can include an advice for traffic direction (even with tc=any).

**Comment by boucadair** [comment]
> 3\. How applications running over a host can learn the bitrates associated with a network attachment. Typically, this can be achieved by invoking a dedicated API. However, the exact details of the API is OS-specific and, thus, out of scope of this document.
> 
> Comment> It is not clear whether OS-specific APIs are required not. I would remove the last line. MASQUE and QUIC based proposals don't require OS-specific API.

I'm not sure about this claim for MASQUE/etc. Please refer to https://datatracker.ietf.org/doc/draft-eddy-scone-api/

**Comment by boucadair** [comment]
> 5\. I don't see a need for "Security Considerations" Section to focus on DDoS.

DDoS is provided as an example to illustrate the use of rate limit + mention that other mechanisms can be used. This is a sec cons section. Anyway, will soften these mentions.

**Comment by boucadair** [comment]
> 7\. Adaptive Application Behavior: : Discovery of intentional policy applied on network attachements when such information is not made available during the service activation or when network upgrades are performed. Adaptive applications will use the information to adjust their behavior. : Concretely, applications are supposed to have access to all throughput advice instances and would, thus, adjust their behavior as a function of scope and traffic category indicated in a throughput policy (all traffic, streaming, etc.). An application that couples multiple flow types will adjust each flow type to be consistent with the specific policy for the relevant traffic category. : Likewise, a host with multiple network attachments may use the discovered throughput advice instances over each network attachment to decide how to distribute its flows over these network attachments (prefer a network attachment to place an application session, migrate connection, etc.). That's said, this document does not make any recommendation about how a receiving host uses the discovered policy.
> 
> Comment> I see the discussion on traffic category (which can be avoided for now).

OK, done at https://github.com/boucadair/draft-xxx-ac-rate-policy-discovery/pull/73/files#diff-ab358ab0ffa13e672eedeaa457634187ee628bbab438b0bafd7df2d648ef7e4b

**Comment by boucadair** [comment]
> Yes, but the draft does not define a "specific traffic category". The following line can be removed:
> Each of these instances may cover a specific traffic category.

ACK. See #75

**Comment by sridharangirish91** [comment]
> > 3. How applications running over a host can learn the bitrates associated with a network attachment. Typically, this can be achieved by invoking a dedicated API. However, the exact details of the API is OS-specific and, thus, out of scope of this document.
> > Comment> It is not clear whether OS-specific APIs are required not. I would remove the last line. MASQUE and QUIC based proposals don't require OS-specific API.
> 
> I'm not sure about this claim for MASQUE/etc. Please refer to https://datatracker.ietf.org/doc/draft-eddy-scone-api/

I agree an API (framework) would be required but doesn't that delve into implementation details and is that needed in a blob definition draft though?

**Comment by boucadair** [comment]
> > > 3. How applications running over a host can learn the bitrates associated with a network attachment. Typically, this can be achieved by invoking a dedicated API. However, the exact details of the API is OS-specific and, thus, out of scope of this document.
> > >    Comment> It is not clear whether OS-specific APIs are required not. I would remove the last line. MASQUE and QUIC based proposals don't require OS-specific API.
> > 
> > 
> > I'm not sure about this claim for MASQUE/etc. Please refer to https://datatracker.ietf.org/doc/draft-eddy-scone-api/
> 
> I agree an API (framework) would be required but doesn't that delve into implementation details and is that needed in a blob definition draft though?

This is typically why the current text says this is out of scope.

**Comment by tireddy2** [comment]
> > > > 3. How applications running over a host can learn the bitrates associated with a network attachment. Typically, this can be achieved by invoking a dedicated API. However, the exact details of the API is OS-specific and, thus, out of scope of this document.
> > > >    Comment> It is not clear whether OS-specific APIs are required not. I would remove the last line. MASQUE and QUIC based proposals don't require OS-specific API.
> > > 
> > > 
> > > I'm not sure about this claim for MASQUE/etc. Please refer to https://datatracker.ietf.org/doc/draft-eddy-scone-api/
> > 
> > 
> > I agree an API (framework) would be required but doesn't that delve into implementation details and is that needed in a blob definition draft though?
> 
> This is typically why the current text says this is out of scope.

I prefer to remove the the bullet: How applications running over a host can learn the bitrates associated with a network attachment. Typically, this can be achieved by invoking a dedicated API. However, the exact details of the API is OS-specific and, thus, out of scope of this document.

It is an unnecessary distraction not relevant to the draft. The WG may adopt a solution like TRAIN which does not require any OS-specific API. I don't see how this bullet is useful to progress the draft.
