### ISSUE TITLE
Comments on SCONE Analysis

### ISSUE THREAD

**Issue by tireddy2** [boucadair/draft-xxx-ac-rate-policy-discovery#76]
1.

Atomic configuration: characterizes whether the throughput advice can be learned using very few packets and whether any change of the policy would require to full policy to be shared or only the relevant instance.

Comment> I can't parse the last part of the line. I suggest the following text:

Atomic configuration: Indicates whether the throughput advice can be learned using very few packets and whether changes to the policy require sharing the entire policy or just the relevant part.

2. Replace "Guard against random advice injection" with "Guard against random advice injection by an on-path attacker".

3. We will have to elaborate "Mobility (guard against changing 5-tuple)". please elaborate the attack.
   I presume you are referring to a scenario where an malicious app keeps changing the 5-tuple to evade rate-limit enforcement by the   
   network.

4. what is meant by "proactive signaling" ?

5. Applicable to any transport protocol => I suggest to remove it, the charter is specific to QUIC, I don't think a solution will be selected solely on the basis that it is applicable for other transport.

6. We may want to explain the meaning of "cascaded environments"

7. Require flow inspection and tracking (network)

Comment> How does inspecting the QUIC flow impact security and how is tracking possible ?

8. What do you mean "Require steering policies on the host" ?

9. I would change "Overhead of unauthenticated re-encryption" to "Overhead of double encryption"
   The status of https://datatracker.ietf.org/doc/draft-ietf-masque-quic-proxy/ is experimental, It also discusses "identity" mode which  
   does not modify the packet in any way.

10. we should also include protocol ossification, zero-trust security (authorized network element must provide the throughput advice), privacy (does not reveal any details about the app and server identity).

**Comment by boucadair** [comment]
> Atomic configuration: characterizes whether the throughput advice can be learned using very few packets and whether any change of the policy would require to full policy to be shared or only the relevant instance.
> 
> Comment> I can't parse the last part of the line. I suggest the following text:
> 
> Atomic configuration: Indicates whether the throughput advice can be learned using very few packets and whether changes to the policy require sharing the entire policy or just the relevant part.
> 

ACK.

> 2. Replace "Guard against random advice injection" with "Guard against random advice injection by an on-path attacker".

ACK

> 3. We will have to elaborate "Mobility (guard against changing 5-tuple)". please elaborate the attack.
>    I presume you are referring to a scenario where an malicious app keeps changing the 5-tuple to evade rate-limit enforcement by the
>    network.

ACK

> 4. what is meant by "proactive signaling" ?

described under updatability bullet. The network can update the advice at any time, without requiring an action from the host

> 5. Applicable to any transport protocol => I suggest to remove it, the charter is specific to QUIC, I don't think a solution will be selected solely on the basis that it is applicable for other transport.

ACK.

> 6. We may want to explain the meaning of "cascaded environments"

Added new text 

> 7. Require flow inspection and tracking (network)
> 
> Comment> How does inspecting the QUIC flow impact security and how is tracking possible ?
> 

That's up to the solutions to explain how. some of the solutions require detecting the initial packet, etc.

> 8. What do you mean "Require steering policies on the host" ?

For MASQUE for example, a host need to decide which flows will need to be steered over the tunnel (sic).

> 9. I would change "Overhead of unauthenticated re-encryption" to "Overhead of double encryption"
>    The status of https://datatracker.ietf.org/doc/draft-ietf-masque-quic-proxy/ is experimental, It also discusses "identity" mode which
>    does not modify the packet in any way.

Removed it as we do have multiple encryption item.

> 10. we should also include protocol ossification, zero-trust security (authorized network element must provide the throughput advice), privacy (does not reveal any details about the app and server identity).

Good points. Please check the PR
