### ISSUE TITLE
Another comment on the Analysis

### ISSUE THREAD

**Issue by tireddy2** [boucadair/draft-xxx-ac-rate-policy-discovery#78]
1. 
To that aim, NRLP:

    Requires an OS API to expose the signal to applications, and ensure application fairness: An OS can provide more accurate available bandwidth to applications through the API, making implementation easier for applications that don't require dedicated bandwidth measurement.

Comment> It will be considered as an disadvantage of NRLP. If PvD is used, the app just needs to learn the PVD ID from OS (which is not specific to NRLP) and the PvD additional information can be retrieved by the app itself (without any dependency on OS). I prefer a solution where OS is involved, but that does not mean NRLP cannot be deployed without any support from OS.

**Comment by boucadair** [comment]
fair comment. fixed in #79
