### ISSUE TITLE
Subscriber specific rate-limit policies

### ISSUE THREAD

**Issue by tireddy2** [boucadair/draft-xxx-ac-rate-policy-discovery#82]
Each subscriber in a mobile network may have different QoS policies depending on their subscription plan. Similarly, in home networks, devices can be assigned different priorities, see https://www.tp-link.com/in/support/faq/1601/. Furthermore, Cisco routers support user-group-based QoS policies, enabling tailored traffic prioritization for user groups (https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_pi/configuration/15-mt/iri-15-mt-book/iri-sgt-based-qos.pdf).

The NRLP draft should discuss mechanisms like solicited Router Advertisements (RAs) https://www.rfc-editor.org/rfc/rfc8273.txt and DHCP responses that enable unique rate-limit configurations per endpoint. Without addressing it, the scope of the draft will be restricted to applying a common rate-limit policy for all endpoints attached to the network.

**Comment by boucadair** [comment]
> Each subscriber in a mobile network may have different QoS policies depending on their subscription plan. Similarly, in home networks, devices can be assigned different priorities, see https://www.tp-link.com/in/support/faq/1601/. Furthermore, Cisco routers support user-group-based QoS policies, enabling tailored traffic prioritization for user groups (https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_pi/configuration/15-mt/iri-15-mt-book/iri-sgt-based-qos.pdf).

ACK, I'm afraid this will introduce more complexity at this stage for the scone case.

FWIW, the full structure of the rate-limit is per type (port, class, node, etc.) as defined in draft-ietf-opsawg-teas-attachment-circuit, for example:

  ```
            +--rw svc-pe-to-ce-bandwidth {vpn-common:inbound-bw}?
              |  +--rw bandwidth* [bw-type]
              |     +--rw bw-type      identityref
              |     +--rw (type)?
              |        +--:(per-cos)
              |        |  +--rw cos* [cos-id]
              |        |     +--rw cos-id    uint8
              |        |     +--rw cir?      uint64
              |        |     +--rw cbs?      uint64
              |        |     +--rw eir?      uint64
              |        |     +--rw ebs?      uint64
              |        |     +--rw pir?      uint64
              |        |     +--rw pbs?      uint64
              |        +--:(other)
              |           +--rw cir?   uint64
              |           +--rw cbs?   uint64
              |           +--rw eir?   uint64
              |           +--rw ebs?   uint64
              |           +--rw pir?   uint64
              |           +--rw pbs?   uint64
              +--rw svc-ce-to-pe-bandwidth {vpn-common:outbound-bw}?
              |  +--rw bandwidth* [bw-type]
              |     +--rw bw-type      identityref
              |     +--rw (type)?
              |        +--:(per-cos)
              |        |  +--rw cos* [cos-id]
              |        |     +--rw cos-id    uint8
              |        |     +--rw cir?      uint64
              |        |     +--rw cbs?      uint64
              |        |     +--rw eir?      uint64
              |        |     +--rw ebs?      uint64
              |        |     +--rw pir?      uint64
              |        |     +--rw pbs?      uint64
              |        +--:(other)
              |           +--rw cir?   uint64
              |           +--rw cbs?   uint64
              |           +--rw eir?   uint64
              |           +--rw ebs?   uint64
              |           +--rw pir?   uint64
              |           +--rw pbs?   uint64
```




> The NRLP draft should discuss mechanisms like solicited Router Advertisements (RAs) https://www.rfc-editor.org/rfc/rfc8273.txt and DHCP responses that enable unique rate-limit configurations per endpoint. Without addressing it, the scope of the draft will be restricted to applying a common rate-limit policy for all endpoints attached to the network.

The network cannot mandate how resources will be partitioned within a local network because that's out of its administration scope. The signal that we are providing right now is a good progress: "this is an aggregate that is shared with others". 

Are there specific considerations you have in mind that we can better indicate?

**Comment by tireddy2** [comment]
> > The NRLP draft should discuss mechanisms like solicited Router Advertisements (RAs) https://www.rfc-editor.org/rfc/rfc8273.txt and DHCP responses that enable unique rate-limit configurations per endpoint. Without addressing it, the scope of the draft will be restricted to applying a common rate-limit policy for all endpoints attached to the network.
> 
> The network cannot mandate how resources will be partitioned within a local network because that's out of its administration scope. The signal that we are providing right now is a good progress: "this is an aggregate that is shared with others".
> 
> Are there specific considerations you have in mind that we can better indicat



> > Each subscriber in a mobile network may have different QoS policies depending on their subscription plan. Similarly, in home networks, devices can be assigned different priorities, see https://www.tp-link.com/in/support/faq/1601/. Furthermore, Cisco routers support user-group-based QoS policies, enabling tailored traffic prioritization for user groups (https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_pi/configuration/15-mt/iri-15-mt-book/iri-sgt-based-qos.pdf).
> 
> ACK, I'm afraid this will introduce more complexity at this stage for the scone case.
> 
> FWIW, the full structure of the rate-limit is per type (port, class, node, etc.) as defined in draft-ietf-opsawg-teas-attachment-circuit, for example:
> 
> ```
>           +--rw svc-pe-to-ce-bandwidth {vpn-common:inbound-bw}?
>             |  +--rw bandwidth* [bw-type]
>             |     +--rw bw-type      identityref
>             |     +--rw (type)?
>             |        +--:(per-cos)
>             |        |  +--rw cos* [cos-id]
>             |        |     +--rw cos-id    uint8
>             |        |     +--rw cir?      uint64
>             |        |     +--rw cbs?      uint64
>             |        |     +--rw eir?      uint64
>             |        |     +--rw ebs?      uint64
>             |        |     +--rw pir?      uint64
>             |        |     +--rw pbs?      uint64
>             |        +--:(other)
>             |           +--rw cir?   uint64
>             |           +--rw cbs?   uint64
>             |           +--rw eir?   uint64
>             |           +--rw ebs?   uint64
>             |           +--rw pir?   uint64
>             |           +--rw pbs?   uint64
>             +--rw svc-ce-to-pe-bandwidth {vpn-common:outbound-bw}?
>             |  +--rw bandwidth* [bw-type]
>             |     +--rw bw-type      identityref
>             |     +--rw (type)?
>             |        +--:(per-cos)
>             |        |  +--rw cos* [cos-id]
>             |        |     +--rw cos-id    uint8
>             |        |     +--rw cir?      uint64
>             |        |     +--rw cbs?      uint64
>             |        |     +--rw eir?      uint64
>             |        |     +--rw ebs?      uint64
>             |        |     +--rw pir?      uint64
>             |        |     +--rw pbs?      uint64
>             |        +--:(other)
>             |           +--rw cir?   uint64
>             |           +--rw cbs?   uint64
>             |           +--rw eir?   uint64
>             |           +--rw ebs?   uint64
>             |           +--rw pir?   uint64
>             |           +--rw pbs?   uint64
> ```
> 
> > The NRLP draft should discuss mechanisms like solicited Router Advertisements (RAs) https://www.rfc-editor.org/rfc/rfc8273.txt and DHCP responses that enable unique rate-limit configurations per endpoint. Without addressing it, the scope of the draft will be restricted to applying a common rate-limit policy for all endpoints attached to the network.
> 
> The network cannot mandate how resources will be partitioned within a local network because that's out of its administration scope. The signal that we are providing right now is a good progress: "this is an aggregate that is shared with others".
> 
> Are there specific considerations you have in mind that we can better indicate?

It will be helpful to explicitly mention how such endpoint-specific mechanism already supported by DHCP/RA will complement the current aggregate approach. I suggest adding text to say the proposed mechanism also works for endpoint-specific signaling which would provide additional granularity (similar to the way MASQUE and QUIC based solutions). I propose the following text:

To enhance flexibility in applying rate-limiting policies and better accommodate diverse endpoint QoS requirements, mechanisms such as solicited Router Advertisements (RAs) [RFC 8273] and endpoint-specific DHCP responses can be employed. These unicast responses enable granular signaling of rate-limit policies to individual endpoints, facilitating differentiated rate-limit configurations. However, this draft does not prescribe how resources should be partitioned within local networks, as such considerations fall outside its scope.
